FROM --platform=${TARGETPLATFORM} golang:1.25.0 as builder

ARG CGO_ENABLED=0

COPY ./ /root/src/
WORKDIR /root/src/
RUN go build -ldflags "-s -w -X main.version=$(git describe --tags --long --always)" -trimpath -o mosdns


FROM --platform=${TARGETPLATFORM} alpine:latest

COPY --from=builder /root/src/mosdns /usr/bin/
WORKDIR /etc/mosdns
COPY --from=builder /root/src/webui ./webui

RUN apk add --no-cache ca-certificates
